### ISSUE TITLE
What methods?

### ISSUE THREAD

**Issue by pmjones** [payload-interop/payload-interop#1]
What methods should be exposed by an interoperable Domain Payload interface?

**Comment by geggleto** [comment]
```
public function toArray() : array;
public function jsonSerialize() : array;
public static function deserialize($data)
```

**Comment by pmjones** [comment]
## Relevant Reading Implementation Methods

### Aura

getStatus() : mixed
getInput() : mixed
getOutput() : mixed
getMessages() : mixed
getExtras() : mixed

### Adroit/Adrenaline

getType() : string
getValue($key, $default = null) : mixed
getValues() : array
getStatus() : mixed
JsonSerializable

### JoeBengalen

getStatus() : ?mixed
getMessage() : ?string
getInput() : ?mixed
getOutput() : ?mixed

### Dashifen

getType() : string
getSuccess() : bool
getDatum(string $index, $default = null) : ?mixed
getData() : array
reset() : void

### Equip

getStatus() : string
getInput() : array
getOutput() : array
getMessages() : array
getSetting(string $name) : mixed
getSettings() : array

### Geggleto

getStatus() : string
getData() : array

### PerfectOblivion

getStatus() : int
getMessages() : array
getOutput() : array

## Summary of Reading Methods

getData() : array
getData() : array

getDatum(string $index, $default = null) : ?mixed

getExtras() : mixed

getInput() : ?mixed
getInput() : array
getInput() : mixed

getMessage() : ?string
getMessages() : array
getMessages() : array
getMessages() : mixed

getOutput() : ?mixed
getOutput() : array
getOutput() : array
getOutput() : mixed

getSetting(string $name) : mixed
getSettings() : array

getStatus() : ?mixed
getStatus() : int
getStatus() : mixed
getStatus() : mixed
getStatus() : string
getStatus() : string

getSuccess() : bool

getType() : string
getType() : string

getValue($key, $default = null) : mixed
getValues() : array

reset() : void

**Comment by pmjones** [comment]
Given the above listing of reading methods, this seems like a reasonable summary of commonalities:

```
getStatus() : string
getInput() : array
getOutput() : array /* as vs getData() and getValues() */
getMessages() : array
```

**Comment by pmjones** [comment]
Additionally, though it is not present in any public implementation, it may be that a `getException() : Throwable` method may be useful; exceptional failures strike me as something that warrants its own special treatment separately from `getOutput()`.

**Comment by niden** [comment]
> Additionally, though it is not present in any public implementation, it may be that a getException() : Throwable method may be useful; exceptional failures strike me as something that warrants its own special treatment separately from getOutput().

`getException()` or `getError()` ? I could see the need to "throw" an error without the presence of an exception. Perhaps something like this:

`public function getError(): array`

```
[
    'type' => 'Exception'
    'message' => 'Blah'
    'object' => new Exception()
]
```

Thoughts?

**Comment by pmjones** [comment]
Designing a new method without any previous public implementations is a difficult thing, with lot of opportunity to get it wrong.

For my part, *if* we pursue something like a error-reporting method, I'd prefer it to be as straightforward and obvious as possible. Among other things, I think that means `getException()` for exceptional failures, whereas a "normal" error might better be represented in `getOutput()`.

Having said that, I would be fine with, say, `getError() : Throwable` instead of calling it getException(), but I do think the latter is more "obvious" as to what you are getting back.

**Comment by niden** [comment]
Thanks for the explanation. `getException()` makes more sense than `getError()` in terms of context.

**Comment by dashifen** [comment]
I'm not sure how much I have to offer here since I was mostly dabbling, but I wish you all luck in your efforts!

**Comment by pmjones** [comment]
Summarized in IMPLEMENTATIONS.
