### ISSUE TITLE
Immutable?

### ISSUE THREAD

**Issue by pmjones** [payload-interop/payload-interop#3]
Should an interoperable Domain Payload be defined as immutable?

**Comment by pmjones** [comment]
Since "true" immutability is not possible in PHP, my thought is "no."

**Comment by shochdoerfer** [comment]
Good point. While you are right that "true" immutability is not possible in PHP, I would still prefer it for the sake of consistency with PSR-7.

**Comment by geggleto** [comment]
Domain Payloads can be "transformable" but not persisted, at least imo.

**Comment by pmjones** [comment]
On further consideration, this might not be a question we need to address at all. @jakejohns in Aura.Payload_Interface suggested splitting the interface into "read" and "write" portions; this was accepted and merged. Immutability would affect only the "write" portions of an interoperable interface; perhaps we need only concentrate on the "getter" portions, thereby obviating the issue.

**Comment by pmjones** [comment]
A second point on restricting the interface (if we go through with this) to the "reading" portions only: it leaves the Domain-specific setting of values up to the Domain. The Responder (or other receiver of the Payload) needs only to be able to read those values out, not set them.

**Comment by dashifen** [comment]
As I've used payloads, that's essentially the way it works.  In short, the Domain stuffs data into them and then the rest of the system reads stuff out of them.  As @geggleto mentioned above, I do use a Transformer object when necessary to mess with the contents of the Payload, but all it does is change them, not add to or remove them.

**Comment by dashifen** [comment]
To be fair, though, I've pretty much only used an ADR-esque framework twice (once in a master class and once for a side project).  I'm not sure i have the domain experience (pun somewhat intended) to lend that much weight to the way I've done things.

**Comment by dashifen** [comment]
Actually, that's not entirely accurate.  my Action objects sometimes add a bit to the Payload based on the needs of the Response.  E.g., if the domain responds with a Payload, but the Response needs some clarifying instructions, those instructions might be added by the Action to the Payload and then passed to the Response.

**Comment by pmjones** [comment]
@dashifen I'd be interested to see examples of that.

**Comment by dashifen** [comment]
https://github.com/dashifen/shadowlab/blob/master/src/Framework/Action/AbstractAction.php#L217

That method does it.  The Payload is received from the Domain on line 223, the data is extracted, and then if it represents a success case, its data is merged with the requirements of the Response template on line 237.  The merged data is crammed back into the Payload on line 245, and then it's all passed to the Response on 247.

The data added during the merge is all specific items needed by the Response.  For example, this is the success template: https://github.com/dashifen/shadowlab/blob/master/views/write/success.html.  I'm using Vue.js on the front end, so all of those {{ variables }} get filled in base don the data the Response finds in the Payload.

**Comment by pmjones** [comment]
@dashifen Ah so. If you'll pardon me, that seems a little heavy for an Action. Some of that can be avoided by having one Action per class; then, one Responder per Action (or per type-of-Action, to consolidate Responders). But, this does tell me where you're coming from -- thanks.

**Comment by dashifen** [comment]
Yeah, it's a work in progress.  A lot of that used to be a higher level in that application and I recently moved it lower (i.e. to the AbstractAction).  I'm not real happy with the overall structure yet, but it's getting the job done and this is a for-fun project, not a for-profit one, that I'm considering a learning tool.

**Comment by pmjones** [comment]
Some notes on which implementations are mutable:

- Mutable: Adroit/Adrenaline, JoeBengalen, Dashifen, Geggleto, PerfectOblivion
- Separate Read/Write: Aura (but combined at implementation, so mutable impl)
- Immutable: Equip

**Comment by pmjones** [comment]
Settled on defining only the "read" interface, not the "write" or "mutate" interface, rendering this discussion moot.
