### ISSUE TITLE
Status constants in separate interface/class?

### ISSUE THREAD

**Issue by pmjones** [payload-interop/payload-interop#6]
Should the constants from #2 be part of the read methods interface, or should they be in a class/interface of their own?

If in the method interface, should they be prefixed with `STATUS_` ?

**Comment by niden** [comment]
Class of their own is my vote. Keeps things nice and tidy. Usually I create a `Enum` class and put such constants in there.

**Comment by pmjones** [comment]
Yes, the supermajority of the implementations do separate the statuses from the payload objects themselves.
