### ISSUE TITLE
Interface proposal, variation 2

### ISSUE THREAD

**Issue by pmjones** [payload-interop/payload-interop#8]
On further consideration of [this comment](https://github.com/payload-interop/payload-interop/issues/7#issuecomment-568572396), I realize that the variation-1 interface in #7  can be reduced even further, to just `getStatus()` and `getOutput()` (or `getResult()` or something similar). Input, messages, and exception values can all be placed in the `getResult()` return. This 2nd variation reflects the reduced/simplified interface.

```php
namespace PayloadInterop;

interface DomainPayload
{
    /**
     * Returns the domain status.
     */
    public function getStatus() : string;

    /**
     * Returns the result produced by the domain as key-value pairs,
     * generally entities or aggregates, but also messages, filtered
     * inputs, and exception objects.
     */
    public function getResult() : array;
}

class DomainStatus
{
    /**
     * Input accepted for later processing.
     */
    const ACCEPTED = 'ACCEPTED';

    /**
     * Create succeeded.
     */
    const CREATED = 'CREATED';

    /**
     * Delete succeeded.
     */
    const DELETED = 'DELETED';

    /**
     * Generic error.
     */
    const ERROR = 'ERROR';

    /**
     * Find succeeded.
     */
    const FOUND = 'FOUND';

    /**
     * Input not valid.
     */
    const INVALID = 'INVALID';

    /**
     * Find failed (n.b.: not an error).
     */
    const NOT_FOUND = 'NOT_FOUND';

    /**
     * Processing is not finished yet.
     */
    const PROCESSING = 'PROCESSING';

    /**
     * Generic success.
     */
    const SUCCESS = 'SUCCESS';

    /**
     * Interaction is not authorized.
     */
    const UNAUTHORIZED = 'UNAUTHORIZED';

    /**
     * Update succeeded.
     */
    const UPDATED = 'UPDATED';

    /**
     * Disallow instantiation.
     */
    final private function __construct() {}
}
```

**Comment by niden** [comment]
Much cleaner - removes ambiguity also on _what should i use X for_

**Comment by pmjones** [comment]
@cherifGSoul @dashifen @devcircus @geggleto @JoeBengalen @niden @pavarnos @priskz  @shochdoerfer @jakejohns You have all commented on the payload-interop project at some point; what is your assessment of this "reduced" interface, as vs the more expanded one in #7?

Thanks, and merrry Christmas!

**Comment by cherifGsoul** [comment]
I like this reduced version is easy to reason about especially for `getResult`.

**Comment by pavarnos** [comment]
Thanks Paul. I'm unlikely to use this now. I have discovered phpstan and really like strictly typing all the things because it finds bugs that would otherwise be hidden or hard to see. It makes refactorings very easy too. The `DomainPayload::getResult()` above is not strict enough for phpstan type checking and phpStorm refactorings.

**Comment by pmjones** [comment]
@pavarnos Noted, and thanks. If you have suggestions for something more typable/hintable, that might work well as a general-purpose situation to move arbitrary Domain objects back across the UI boundary, I'm interested to hear them.

**Comment by pavarnos** [comment]
@pmjones thank you. I've settled on passing database rows to the UI where the data needs are simple. For complicated stuff or where the same data is used in several Actions, I've built custom strongly typed DTOs and factory classes that create them. This has proved robust: I've done some pretty major refactorings very quickly with zero problems. The hardest (riskiest / most bug prone) thing has been adding strict types to untyped code that just returned "array" in the past...

**Comment by pmjones** [comment]
@pavarnos -- I wonder, would renaming `getResult()` to `asArray()` or `toArray()` soothe your concerns here? The idea being that the end-user is encouraged to define typehinted methods on their DomainPayload implementation, with `asArray()` (or whatever) available as part of the standard interface to provide the full payload as key-value pairs. Your thoughts?

**Comment by pavarnos** [comment]
if you had the strictly typed ones, why would you use `asArray()`?

**Comment by pmjones** [comment]
> if you had the strictly typed ones, why would you use asArray()?

Among other things, that makes it easy to send the Payload to template systems in a single call. That's pretty much what I do with the `getResult()` (and its equivalents) currently.

A contrived example:

```php
$template->setData($payload->toArray());
$response->setBody($template->render());
```

In any case, the point is not to argue the benefit of strictly typehinted returns vs array typehints, but to recognize that *existing systems* currently use the array typehint, *and at the same time* make allowance for stricter typing when desired.

**Comment by pavarnos** [comment]
ah. ok thanks. That makes sense to me now.
i'm one of those weirdos who does not use a templating system (eg twig, blade, whatever) because i feel that PHP is already a templating language. I tend to write small utility classes for rendering an html table (eg with all the correct Bootstrap styles automatically included), or a form, or the global nav bar etc and compose those in small testable chunks. Then I don't have a lot of repeated html and css. Which has made it really fast to re-skin my app a couple of times.

**Comment by pmjones** [comment]
@pavarnos -- fair enough. The next question, then, is this: how much would you object to keeping the name `getResult()`, as vs something like `toArray()` or `asArray()`?

**Comment by pmjones** [comment]
@dashifen @devcircus @geggleto @JoeBengalen @priskz @shochdoerfer @jakejohns Sorry for the noise -- any thoughts or comments here?

**Comment by priskz** [comment]
I’ve been lurking and enjoy the discussion. I created the Priskz/payload package, very basic and wasn’t really ever intended to be used by others, so I appreciate you posting it as an option. Personally, I would avoid the “toArray” method because it implies implementation details. I don’t mind the “toArray” as an abstract “helper” method that is defined “per language”, so I would prefer the getResult in this scenario. On my payload I just used getData and getStatus. To me “result” is more or less the same as “data”.

**Comment by shochdoerfer** [comment]
I am fine with `getResult()` as it currently is, sure some more strict type hinted definition would be nice but I guess hard to implement given how "different" domains can be.

**Comment by pmjones** [comment]
All -- I have summarized these responses, and the proposed interface, as a README and source code as of this commit: https://github.com/payload-interop/payload-interop/tree/d0f2676112884bddc2a194a9f5ff2d12e71bcac8

At this point I think we are ready for a more public review period; I will post on my blog and perhaps elsewhere to encourage others to take a look.

If you have other comments/questions/concerns/etc, please bring them up as you find convenient. Meanwhile, many thanks to everyone here for their input and efforts on this project!
