### ISSUE TITLE
Turn DomainStatus into an interface

### ISSUE THREAD

**Issue by schlessera** [payload-interop/payload-interop#9]
The `DomainStatus` is currently a [class](https://github.com/payload-interop/payload-interop/blob/81c594154b17d4bace2cddb428622a2f36860eca/src/DomainStatus.php#L6) that regroups constants.

At the bottom of the file, it adds a [private constructor](https://github.com/payload-interop/payload-interop/blob/81c594154b17d4bace2cddb428622a2f36860eca/src/DomainStatus.php#L66) so as to prohibit instantiation.

As this class...
- is not meant to be instantiated; and
- serves the purpose of defining a contract between different parties using the payload

... I suggest turning it into an `interface` instead of a non-instantiatble class.

**Comment by pmjones** [comment]
Hi @schlessera,

First, thanks for taking the time to review. Now:

My research indicates that an interface of only constants is regarded negatively, whether merely "distasteful" or an actual antipattern. Cf., among others:

- https://infogalactic.com/info/Constant_interface
- https://stackoverflow.com/questions/2659593/what-is-the-use-of-interface-constants
- http://www.javapractices.com/topic/TopicAction.do?Id=32
- https://softwareengineering.stackexchange.com/questions/49572/is-it-a-bad-practice-to-have-an-interface-to-define-constants
- https://dzone.com/articles/constants-in-java-the-anti-pattern-1

Granted, that's all Java, but I think the points all hold for PHP.

Having said that, can you link to literature that supports interfaces composed only of constants? I'm happy to review and revisit this decision, if warranted.

**Comment by schlessera** [comment]
Hey @pmjones,

The anti-pattern from the Java space you're linking to is not exactly the same as in PHP, and the drawbacks are not the same in PHP. I'd argue that in PHP, the `interface` version has less drawbacks and is cleaner.

First let me describe the main difference between the constants interface (anti-)pattern, as it is used in Java, and what I'm proposing.

In Java, you actually implement the interface with the constants to get access to them. Then, within the class that implements the interface, the constants are used as-is (without any prefix, namespace or other distinguishing factor), so you can't really tell where they're coming from.

In PHP, however, you wouldn't implement that interface, at least the way I'm suggesting to use it. You just make static use of its constants. It is merely a contract between two parties to agree on the semantic meaning of value.

Access in Java:
```java
public class MyDomainPayload implements DomainPayload, DomainStatus {

	public string getStatus() {
		return ACCEPTED;
	}
}
```

Access in PHP:
```php
public class MyDomainPayload implements DomainPayload {

	public string getStatus() {
		return DomainStatus::ACCEPTED;
	}
}
```

Let me address the individual points that are raised in the [https://infogalactic.com/info/Constant_interface](https://infogalactic.com/info/Constant_interface) article now.

- > since constants are very often merely an implementation detail, and the interfaces implemented by a class are part of its exported API, this practice amounts to putting implementations details into the API, which was considered inappropriate

We are not implementing the interface, we are just using it. Also, it is provided as part of an interop package here, so whether it is in a class or an interface, it is already beyond an implementation detail and part of an interface anyway.

- > It pollutes the class namespace with read-only variables that may not be of use.

Not applicable here, as we don't implement the interface, and only refer to the constants via the FQCN or imported relative name of the interface.

- > Contrary to the compile-time tactical utility of implementing a constants interface, the incidental run-time artifacts have little practical purpose.

This does not apply here, again, as we're not implementing the interface. We are doing a static access to a constant provided in a different class/interface.

- > If binary code compatibility is required in future releases, the constants interface must remain forever an interface

Not applicable for PHP.

- > Without an IDE that resolves where the constant are coming from, tracking it back to its containing class or interface can be time consuming

This doesn't apply here, as we're directly referencing the source interface to access the constants, making it obvious where they are coming from.

- > A variable (representing an instance) of the interface is syntactically no more useful than the interface name itself (since it has no methods).

Not applicable here, as we are only using the interface name directly in PHP and not instantiating it.

- > Unless a developer checks any implemented interfaces when adding a constant to a class, or does so but makes a typo in the new constant's name, the value of a constant can be silently changed.

Once more, this doesn't apply here, as we don't implement the interface. It cannot be silently changed, as that would mean trying to modify the interface itself.

Hopefully, the above shows that the "constants interface" antipattern in Java is not what I have suggested here, and none of the drawbacks apply to a PHP interface which is used to provide static access to constants across components.

**Comment by pmjones** [comment]
Fair points! I will seek other opinions before making a call either way; meanwhile, thank you very much for taking the time and effort to put together these arguments.

**Comment by pmjones** [comment]
As a side note @schlessera your article https://www.alainschlesser.com/the-cost-of-contribution/ is excellent.
